/* Auto-generated by genmsg_cpp for file /home/weiweihuang/groovy_workspace/Pathplanning/car_drive_control/msg/motion_command.msg */
#ifndef CAR_DRIVE_CONTROL_MESSAGE_MOTION_COMMAND_H
#define CAR_DRIVE_CONTROL_MESSAGE_MOTION_COMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace car_drive_control
{
template <class ContainerAllocator>
struct motion_command_ {
  typedef motion_command_<ContainerAllocator> Type;

  motion_command_()
  : header()
  , time(0)
  , velocity(0.0)
  , angular(0.0)
  {
  }

  motion_command_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , time(0)
  , velocity(0.0)
  , angular(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _time_type;
  int32_t time;

  typedef float _velocity_type;
  float velocity;

  typedef float _angular_type;
  float angular;


  typedef boost::shared_ptr< ::car_drive_control::motion_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_drive_control::motion_command_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motion_command
typedef  ::car_drive_control::motion_command_<std::allocator<void> > motion_command;

typedef boost::shared_ptr< ::car_drive_control::motion_command> motion_commandPtr;
typedef boost::shared_ptr< ::car_drive_control::motion_command const> motion_commandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::car_drive_control::motion_command_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::car_drive_control::motion_command_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace car_drive_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::car_drive_control::motion_command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::car_drive_control::motion_command_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::car_drive_control::motion_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4d818ac13eeb3e2f364ed9fee86a2669";
  }

  static const char* value(const  ::car_drive_control::motion_command_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4d818ac13eeb3e2fULL;
  static const uint64_t static_value2 = 0x364ed9fee86a2669ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_drive_control::motion_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "car_drive_control/motion_command";
  }

  static const char* value(const  ::car_drive_control::motion_command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::car_drive_control::motion_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 time\n\
float32 velocity\n\
float32 angular\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::car_drive_control::motion_command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::car_drive_control::motion_command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::car_drive_control::motion_command_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::car_drive_control::motion_command_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.time);
    stream.next(m.velocity);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motion_command_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_drive_control::motion_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::car_drive_control::motion_command_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CAR_DRIVE_CONTROL_MESSAGE_MOTION_COMMAND_H

